server:
  port: 30140

mybatis:
  mapper-locations: classpath*:mappers/*.xml,classpath*:**/mapper/common/*Mapper.xml,classpath*:**/mapper/h2/*Mapper.xml
  config-location: classpath:jpaConfig-embedded.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

spring:
  application:
    name: zkc


  main:
    allow-bean-definition-overriding: true

  messages:
    basename: i18n/message
    encoding: UTF-8

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:h2:~/.h2/hbq969/config
      driver-class-name: org.h2.Driver
      username: foo
      password: ENC(2HRE3Jhuz6IfiD8L7orn4flpXNPTWLhH4u6lH/i0SWf8jXh3tNGQG++plhHmJN3F)
      maximum-pool-size: 20
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  kafka:
    producer:
      bootstrap-servers: docker.for.mac.host.internal:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
      buffer-memory: 134217728
      batch-size: 65536
      properties:
        heartbeat.interval.ms: 3000
        max.block.ms: 10000
        #        sasl.mechanism: PLAIN
        #        security.protocol: SASL_PLAINTEXT
        #        sasl.jaas.config: ENC(wfUFL/Omh6mpEt2J/tJteC5jONhfnZD+9hR+4Mc7bnJnKwh6yhC8xMRv6yQl0dJTy5FhGlM7B8ubmI5VLFw6haz9wMBUcKwNkp4X+ktPNNj8OZaGkHvSITTeXS4KhMuNnUE9842xrRtCsqTbUPf+EhxnrrGof9Hnx7BjvgRgdq9CoQGm/dZsKPhY5nKjhU8B)
        retry.backoff.ms: 500
        linger.ms: 1000
        max.in.flight.requests.per.connection: 1
      retries: 120
    consumer:
      enabled: true
      bootstrap-servers: docker.for.mac.host.internal:9092
      enable-auto-commit: true
      auto-commit-interval: 10s
      max-poll-records: 500
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}
      fetch-min-size: 10485760
      fetch-max-wait: 2s
      properties:
        heartbeat.interval.ms: 3000
        max.block.ms: 10000
    #        sasl.mechanism: PLAIN
    #        security.protocol: SASL_PLAINTEXT
    #        sasl.jaas.config: ENC(wfUFL/Omh6mpEt2J/tJteC5jONhfnZD+9hR+4Mc7bnJnKwh6yhC8xMRv6yQl0dJTy5FhGlM7B8ubmI5VLFw6haz9wMBUcKwNkp4X+ktPNNj8OZaGkHvSITTeXS4KhMuNnUE9842xrRtCsqTbUPf+EhxnrrGof9Hnx7BjvgRgdq9CoQGm/dZsKPhY5nKjhU8B)
    listener:
      type: batch
      concurrency: 1
      poll-timeout: 10s

  # 接口缓存
  cache:
    ext:
      enable: true
      juc:
        allow-null-values: true
        max-capacity: 2000

  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}
        port: ${server.port}
        tags: path=/${spring.application.name},port=${server.port},secure=false
        instance-id: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}
        health-check-path: /common/health
        health-check-interval: 10s
      host: localhost
      port: 8500


knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: ENC(mv4p+dUGgUXJ1DKfGvtMyAdqyDAlm1mMZ5DeTSP0OXO6IIk8LErsnpY5T1sThsaM)

swagger:
  api-info:
    enable: true
    title: safebox web应用防护Restful API
    description: safebox web应用防护Restful API
    termsOfServiceUrl: http://127.0.0.1:${server.port}
    version: v1.0
    license: Apache LICENSE-2.0
    licenseUrl: https://apache.org/licenses/LICENSE-2.0.txt

# 数据字典管理
dict:
  enable: false
  dialect: embedded
  db:
    jdbc-url: ${spring.datasource.hikari.jdbc-url}
    driver-class-name: ${spring.datasource.hikari.driver-class-name}
    username: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 600000
    max-lifetime: 800000
    connection-test-query: SELECT 1
  enabled: true

# 分布式锁
lock:
  spi:
    redis:
      enabled: false
      standard:
        host: docker.for.mac.host.internal
        port: 6379

# restful接口加解密
encrypt:
  config:
    enabled: true
  restful:
    aes:
      enabled: false
      charset: utf-8
      show-log: true
      key: x
    rsa:
      enabled: false
      charset: utf-8
      show-log: true
      private-key: x
      public-key: x

# restful接口日志记录
advice:
  log:
    enabled: true
  restful-limit:
    enabled: true

zkUrl: docker.for.mac.host.internal:12181
zkSessionTimeoutMills: 5000