apiVersion: v1
kind: Service
metadata:
  name: zkc-${gray}
  namespace: ${k8s_ns}
  labels:
    app: zkc-${gray}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 30140
      targetPort: 30140
      protocol: TCP
      name: restful
  selector:
    app: zkc-${gray}

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zkc-${gray}
  namespace: ${k8s_ns}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      name: zkc-${gray}
  template:
    metadata:
      labels:
        name: zkc-${gray}
        app: zkc-${gray}
    spec:
      restartPolicy: Always
      volumes:
        - name: safebox-logs
          hostPath:
            path: /apps/logs/zkc-${gray}
      containers:
        - name: zkc-${gray}
          image: ${docker_prefix}/zkc:${tag}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 30140
              path: /common/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          readinessProbe:
            httpGet:
              port: 30140
              path: /common/health
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 240
          resources:
            requests:
              cpu: '0.3'
              memory: 800Mi
            limits:
              cpu: '0.3'
              memory: 1Gi
          volumeMounts:
            - mountPath: /apps/logs
              name: safebox-logs
          ports:
            - containerPort: 30140
          env:
            - name: spring_cloud_zookeeper_enabled
              value: "false"
            - name: spring_cloud_zookeeper_connectString
              value: ""
            - name: spring_cloud_zookeeper_auth_info
              value: ""
            - name: spring_profiles_active
              value: "${spring_profiles_active}"

